/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void testChangeValue() {
        App obj = new App();
        assertEquals(1, obj.calcValue(0, "+1"));
        assertEquals(-1, obj.calcValue(0, "-1"));
        assertEquals(20, obj.calcValue(10, "+10"));
    }
    @Test
    public void testLoadFile() {
        App obj = new App();
        assertEquals("hello world", obj.loadFile("/home/norder/dev/aoc2018/01/test.txt"));
    }
    @Test
    public void testFindRepeat() {
        App obj = new App();
        assertEquals(3, obj.findRepeat("+2\n+1\n+1\n-1"));
        assertEquals(10, obj.findRepeat("+3\n+3\n+4\n-2\n-4"));
    }
}
