/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testCheckRepeat() {
        App app = new App();
        assertEquals(true, app.checkRepeat("abcda".toCharArray(), 2));
        assertEquals(false, app.checkRepeat("abcd".toCharArray(), 2));
        assertEquals(true, app.checkRepeat("abcdacda".toCharArray(), 3));
        assertEquals(false, app.checkRepeat("abcdefghi".toCharArray(), 3));
    }
    @Test public void testCheckSum() {
        App app = new App();
        assertEquals((Integer)4, app.checkSum("aa\naaa\nabc\nbb\nbbb\ncdf"));
        assertEquals((Integer)2, app.checkSum("aa\naaa\nabc\nbb\ncdf"));
    }
    @Test public void testFindString() {
        App a = new App();
        assertEquals("abde", a.findString("abcde\nbdsas\nedsaq\nabade\nfdsap"));
    }
}
