/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.nio.file.*;
import java.util.stream.*;
import java.util.*;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App obj = new App();
        String data = obj.loadFile("/home/norder/dev/aoc2018/01/input.txt");
        String[] array = data.split("\n", -1);
        int x = 0;
        for (int i = 0; i < array.length; i++) {
            x = obj.calcValue(x, array[i]);
        }
        System.out.println(x);
        String data2 = obj.loadFile("/home/norder/dev/aoc2018/01/input2.txt");
        System.out.println(obj.findRepeat(data2));
    }

    public int calcValue(int start, String change) {
        return Integer.parseInt(change) + start;
    }

    public int findRepeat(String data) {
        String[] array = data.split("\n", -1);
        int x = 0;
        Set<Integer> a = new HashSet<Integer>();
        for (int i = 0; i < array.length; i++) {
            x = this.calcValue(x, array[i]);
            if (a.contains(new Integer(x))) return x;
            a.add(new Integer(x));
            if (i == array.length - 1) i = -1;
        }

        return 0;
    }

    public String loadFile(String fileName) {
        try {
            Path path = Paths.get(fileName);
            Stream<String> lines = Files.lines(path);
            String data = lines.collect(Collectors.joining("\n"));
            lines.close();
            return data;
        } catch (Exception ex) {
            return "";
        }
    }
}
